// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIcghO0QFjDj9-Vr351v7PYlzaTwBqcKQ',
    appId: '1:834659197017:web:2d14fbec74f5f7f1fa5148',
    messagingSenderId: '834659197017',
    projectId: 'enia-6d7d9',
    authDomain: 'enia-6d7d9.firebaseapp.com',
    storageBucket: 'enia-6d7d9.firebasestorage.app',
    measurementId: 'G-SDRBSRB00H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3L1TQh4XyVUKmi9Q6Tga79b-QLhg0rg4',
    appId: '1:834659197017:android:03969c666b4593f5fa5148',
    messagingSenderId: '834659197017',
    projectId: 'enia-6d7d9',
    storageBucket: 'enia-6d7d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjyluvDO9lkZIeI8wlD0YPNKGnb5oPaP0',
    appId: '1:834659197017:ios:bcf721fb6fb8dee4fa5148',
    messagingSenderId: '834659197017',
    projectId: 'enia-6d7d9',
    storageBucket: 'enia-6d7d9.firebasestorage.app',
    iosBundleId: 'com.example.enia',
  );

}